/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetoTesteBuider;

import javax.swing.JOptionPane;

public class App {
   
    public static void main(String[] args) {
        String m="1";
        String t="1";
        String d="1";
        String nd="1";
        String d2="0";
        String b="1";
        String me="1";
        String tipo="1";
        
        Computador notebook = new Computador();
        
        tipo = JOptionPane.showInputDialog("Informe o tipo de Notebook: 1 - Básico ou 2 - Personalizado");
        
        if(tipo.equals("1")){
            IBuilderProtocolo note = new BuilderNotebookBasico();
            notebook = note.configura(m, t, d, nd, d2, b, me);
        }
        
        if(tipo.equals("2")){
        IBuilderProtocolo note = new BuilderNotebookPersonalizado(); 
        
        
        
        m = JOptionPane.showInputDialog("Informe o modelo do monitor: 1 - 15 pol ou 2 - 17 pol");
                
        t = JOptionPane.showInputDialog("Informe o modelo do Teclado: 1 - comum ou 2 - retroiluminado");
               
        d = JOptionPane.showInputDialog("Informe o modelo da unidade de armazenamento: 1 - HD ou 2 - SSD");
        
            
        nd = JOptionPane.showInputDialog("Deseja acrescentar uma segunda unidade de armazenamento?: 1 - sim ou 2 - não");
        
        if(nd.equals("1")){
        
         d2 = JOptionPane.showInputDialog("Informe o modelo da unidade de armazenamento: 1 - HD ou 2 - SSD");
        
       }
        
       b = JOptionPane.showInputDialog("Informe o modelo da bateria: 1 - 8 cel, 2 - 10 cel ou 3 - 16 cel");
        
        
        
       me = JOptionPane.showInputDialog("Informe o modelo da Memória: 1 - DDR3 4GB, 2 - DDR4 8GB ou 3 - DDR5 16GB");
       
       notebook = note.configura(m, t, d, nd, d2, b, me);
        }   
       
       
       
       notebook.configuracao_final();
       System.out.println("O preco da configuracao do notebook eh..: "+notebook.getPrice());
        
    }
}
